[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "delete-debug-mg5amcnlo-macos"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[tasks.start]
cmd = "mg5_aMC tutorial.mg5"

[dependencies]
mg5amcnlo = ">=3.5.7,<4"
sed = ">=4.7,<5"
